# -*- coding: utf-8 -*-
"""operators

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dEUf_zjWZ2Ol6NhXW8El0-pfHcNtZZbt
"""

# ======================================
# TOPIC: Mastering Operators in Python
# ======================================


# 1. Arithmatic Operators
# Used with numeric values to perform common mathematical operations
print("--- 1. Arithmatic Operators ---")
a = 15
b = 4

print(f"Addition (15 + 4)                   = {a + b}")
print(f"Subtraction (15 - 4)                = {a - b}")
print(f"Multiplication (15 * 4)             = {a * b}")
print(f"Division (15 / 4)                   = {a / b}")         # Always returns a Float (3.75)
print(f"Floor Division (15 // 4)            = {a // b}")        # Rounds down to nearest whole number (3)
print(f"Modulus/Remainder (15 % 4)          = {a % b}")         # returns the remainder of division (3)
print(f"Exponentiation (15 ** 4)            = {a ** b}")        # 15 to the power of 4
print()

# 2. Assignment Operators
# Used to assign values to variables, often combining math operations for efficiency.
print("--- 2. Assignment Operators ---")
score = 10
print(f"Initial Score: {score}")

score += 5        # Equivalent to: score = score + 5
print(f"After score += 5: {score}")

score *= 2        # Equivalent to: score = score * 2
print(f"After score *= 2: {score}")
print()

# 3. Comparison Operators
# Used to compare two values. They ALWAYS return a boolean value (True or False).
# Extremely crucial for Data Filtering and Conditional Statements (If-Else)
print("--- 3. Comparison Operators ---")
x = 10
y = 20

print(f"Is x equal to y? (10 == 20)             -> {x == y}")
print(f"Is x NOT equal to y? (10 != 20)         -> {x != y}")
print(f"Is x greater than y? (10 > 20)          -> {x > y}")
print(f"Is x less than y? (10 < 20)             -> {x < y}")
print(f"Is x greater or equal? (10 >= 10)       -> {x >= 10}")
print()

# 4. Logical Operators
# Used to combine multiple conditional statements together
print("--- 4. Logical Operators ---")

