# -*- coding: utf-8 -*-
"""operators

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dEUf_zjWZ2Ol6NhXW8El0-pfHcNtZZbt
"""

# ======================================
# TOPIC: Mastering Operators in Python
# ======================================


# 1. Arithmatic Operators
# Used with numeric values to perform common mathematical operations
print("--- 1. Arithmatic Operators ---")
a = 15
b = 4

print(f"Addition (15 + 4)                   = {a + b}")
print(f"Subtraction (15 - 4)                = {a - b}")
print(f"Multiplication (15 * 4)             = {a * b}")
print(f"Division (15 / 4)                   = {a / b}")         # Always returns a Float (3.75)
print(f"Floor Division (15 // 4)            = {a // b}")        # Rounds down to nearest whole number (3)
print(f"Modulus/Remainder (15 % 4)          = {a % b}")         # returns the remainder of division (3)
print(f"Exponentiation (15 ** 4)            = {a ** b}")        # 15 to the power of 4
print()

# 2. Assignment Operators
# Used to assign values to variables, often combining math operations for efficiency.
print("--- 2. Assignment Operators ---")
score = 10
print(f"Initial Score: {score}")

score += 5        # Equivalent to: score = score + 5
print(f"After score += 5: {score}")

score *= 2        # Equivalent to: score = score * 2
print(f"After score *= 2: {score}")
print()

# 3. Comparison Operators
# Used to compare two values. They ALWAYS return a boolean value (True or False).
# Extremely crucial for Data Filtering and Conditional Statements (If-Else)
print("--- 3. Comparison Operators ---")
x = 10
y = 20

print(f"Is x equal to y? (10 == 20)             -> {x == y}")
print(f"Is x NOT equal to y? (10 != 20)         -> {x != y}")
print(f"Is x greater than y? (10 > 20)          -> {x > y}")
print(f"Is x less than y? (10 < 20)             -> {x < y}")
print(f"Is x greater or equal? (10 >= 10)       -> {x >= 10}")
print()

# 4. Logical Operators
# Used to combine multiple conditional statements together
print("--- 4. Logical Operators ---")
has_good_grades = True
has_high_attendance = False

# 'and' returns True ONLY IF both statements are True
print(f"Scholarship Eligibility (AND): {has_good_grades and has_high_attendance}")

# 'or' returns True IF AT LEAST ONE statement is true
print(f"Exam Eligibility (OR): {has_good_grades or has_high_attendance}")

# 'not' reverses the Boolean result (True becomes False, and vice-versa)
print(f"Is student banned? (NOT): {not has_good_grades}")
print()


# 5. Identity Operators (Advanced Concept)
# Used to compare objects, not just values. They check if two variables point to
# the EXACT SAME memory location (linking back to Module 2's Object Reference)
print("--- 5. Identity Operators ---")
list_a = [1, 2, 3]
list_b = [1, 2, 3]
list_c = list_a

# '==' checks if values are identical
print(f"Do list_a and list_b have the same values? (==) -> {list_a == list_b}")

# 'is' checks if they share the exact same memory location
print(f"Are list_a and list_b the exact same object? (is) -> {list_a is list_b}")
print(f"Are list_a and list_c the exact same object? (is) -> {list_a is list_c}")
print()


# 6. Membership Operators
# Used to test if a sequence (like a String, List, or Tuple) contains a specific item
print("--- 6. Membership Operators ---")
target_skills = ["Python", "SQL", "Tableau", "Machine Learning"]

print(f"Is 'Python' in the skill list?     -> {'Python' in target_skills}")
print(f"Is 'Java' missing from the list?   -> {'Java' not in target_skills}")
print()


# 7. Bitwise Operators (Advanced)
# Operations performed directly on binary numbers (bits)
print("--- 7. Bitwise Operators ---")
bin_x = 5    # 0101
bin_y = 3    # 0011
print(f"Bitwise AND (5 & 3)  = {bin_x & bin_y}")
print(f"Bitwise OR (5 | 3)   = {bin_x | bin_y}")
print()


# 8.

