# -*- coding: utf-8 -*-
"""Print()

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v7h4-fz2E3eJeX3a0VS67BjoPrfGrz0f
"""

print("Halo!")
print("Saya sedang belajar coding.")
print("Target saya adalah menjadi Data Scientist.")

print("Aku suka aku")
print("Aku makan nasi goreng")
print("Aku suka makan")
print("oke aku makan")
print("aku lapar")