# -*- coding: utf-8 -*-
"""print() function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v7h4-fz2E3eJeX3a0VS67BjoPrfGrz0f
"""

print("Hello everyone!")
print("I'm learning Python.")
print("I like Asian food that's rich in spices.")
print("I'am a person who learns from experience.")
print("Learning is about improving oneself.")
print()
# ===================================================
# TOPIC: Mastering Python Output Function - print()
# ===================================================

# 1. Escape Characters
# Demonstrating how to create new lines (\n), tabs (\t), and handle quotes
print("---1. Escape Characters---")
print("Hello everyone!\nI'm learning Python.\n\tThis text is intended using a tab.")