# -*- coding: utf-8 -*-
"""print() function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v7h4-fz2E3eJeX3a0VS67BjoPrfGrz0f
"""

print("Hello everyone!")
print("I'm learning Python.")
print("I like Asian food that's rich in spices.")
print("I'am a person who learns from experience.")
print("Learning is about improving oneself.")
print()
# ===================================================
# TOPIC: Mastering Python Output Function - print()
# ===================================================

# 1. Escape Characters
# Demonstrating how to create new lines (\n), tabs (\t), and handle quotes
print("---1. Escape Characters---")
print("Hello everyone!\nI'm learning Python.\n\tThis text is intended using a tab.")
print("Displaying quotation marks: \"Use a backlash before the quote\"")
print()  # Empty print for spacing in the terminal

# 2. The 'sep' (Separator) Parameter
# Customizing the default space separator between multiple arguments
print("--- 2. Separator Parameter ---")
print("Day", "Month", "Year", sep="-")             # Output: Day-Month-Year
print("Alice", "Bob", "Charlie", sep=" , ")        # Output: Alice , Bob , Charlie
print("192", "168", "1", "1", sep=".")             # Output: 192.168.1.1
print()

# 3. The 'end' Parameter
# Appending a custom character at the end instead of the default newline (\n)
print("--- 3. End Parameter ---")
print("Learning Progress: 50%", end="... ")
print("Processing data", end="... ")
print("Completed!")         # These three prints stay on the same line
print()

# 4. String Formatting (f-string)
# The industry standard way to embed variables and expressions inside strings
print("--- 4. String Formatting (f-string) ---")
product_name = "ASUS Laptop"
base_price = 8500000
discount = 0.15

print(f"Product Name: {product_name}")
print(f"Base Price: Rp {base_price}")
print(f"Total Price afer 15% Discount: Rp {base_price * (1 - discount)}")
print()

# 5. Advanced f-string Formatting (Numbers & Currency)
# Formatting thousands separators and limiting decimal places
print("--- 5. Advanced f-string Formatting ---")
salary = 15000000
pi_value = 3.14159265
print(f"Currency Format: Rp {salary:,}")          # Output: Rp 15,000,000
print(f"Decimal Format: {pi_value:.2f}")          # Output: 3.14 (Rounded to 2 decimal places)
print()

# 6. The 'file' Parameter (Writing Output to a Document)
# Redirecting the print output directly into an external text file
print("--- 6. File Parameter ---")
with open("log_notes.txt", "w") as f:
  print("This text is saved automatically inside the file, not in the terminal!", file=f)
print("Task finished. Check 'log_notes.txt' in your folder.")
print()

# 7. The 'flush' Parameter (Forcing Instant Output)
# Forcing Python to display the text immediately without buffering (Great for animations)
print("--- 7. Flush Parameter ---")
import time

print("Loading", end="", flush=True)
for i in range(3):
  time.sleep(1)
  print(".", end="", flush=True)          # Dots appear one by one every 1 second
print()