# -*- coding: utf-8 -*-
"""Variables

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQz3XgyCJz3UgGFtbDq8K8z7V3Z4Bzov
"""

Message="Say hello on the counting of..."
Counting=321
Last_Counting=0.5
Say=True
No_say=False

print(Message)
print(Counting)
print(Last_Counting)
print(Say)
print(No_say)

