# -*- coding: utf-8 -*-
"""Variables and Data Types

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQz3XgyCJz3UgGFtbDq8K8z7V3Z4Bzov
"""

# ===========================================
# TOPIC: Variables and Data Types in Python
# ===========================================

# 1. Variable Assignment & Naming Conventions (PEP 8)
# Variables are containers for storing data values
# Python uses snake_case for variable names (lowercase with underscores)
print("--- 1. Variable Assignment ---")
user_name = "Alice"         # Valid snake_case
total_score = 95            # Clear and descriptive name
is_active = True            # Boolean variable naming style

print(f"User Name: {user_name}, Score: {total_score}, Active: {is_active}")
print()

# 2. Basic Data Types (String, Integer, Float, Boolean)
# Demonstrating the 4 core fundamental data types in Python
print("--- 2. Core Data Types ---")
product_title = "Wireless Mouse"        # String (str) -> Text wrapped in quotes
stock_quantity = 45                     # Integer (int) -> Whole numbers without decimals
product_price = 19.99                   # Float (float) -> Numbers with decimal points
is_available = True                     # Boolean (bool) -> True or False (Case-sensitive)

print(f"Title Type: {type(product_title)}")
print(f"Stock Type: {type(stock_quantity)}")
print(f"Price Type: {type(product_price)}")
print(f"Availability Type: {type(is_available)}")
print()

# 3. Dynamic Typing
# Python is dynamically typed, meaning a variable can change its data type at any time
print("--- 3. Dynamic Typing ---")
data_holder = 100
print(f"Initial Value: {data_holder} | Type: {type(data_holder)}")
print()

# 4. Multiple Assignment
# Assigning multiple variables in a single line of code for efficiency
print(--- 4. Multiple Assignment ---)
# Assigning different values to different variables
x, y, z = 10, 20, 30
print(f"x: {x}, y: {y}, z: {z}")

# Assigning the same value to multiple variables at once
gold_score = silver_score = bronze_score = 100
print(f"Gold: {gold_score}, Silver: {silver_score}, Bronze: {bronze_score}")
print()

# 5. Type Casting (Data Type Conversion)
#

