# -*- coding: utf-8 -*-
"""variables and data Types

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQz3XgyCJz3UgGFtbDq8K8z7V3Z4Bzov
"""

# ===========================================
# TOPIC: Variables and Data Types in Python
# ===========================================

# 1. Variable Assignment & Naming Conventions
# Variables are containers for storing data values
# Python uses snake_case for variable names (lowercase with underscores)
print("--- 1. Variable Assignment ---")
user_name = "Alice"         # Valid snake_case
total_score = 95            # Clear and descriptive name
is_active = True            # Boolean variable naming style

print(f"User Name: {user_name}, Score: {total_score}, Active: {is_active}")
print()

# 2. Basic Data Types (String, Integer, Float, Boolean)
# Demonstrating the 4 core fundamental data types in Python
print("--- 2. Core Data Types ---")
product_title = "Wireless Mouse"        # String (str) -> Text wrapped in quotes
stock_quantity = 45                     # Integer (int) -> Whole numbers without decimals
product_price = 19.99                   # Float (float) -> Numbers with decimal points
is_available = True                     # Boolean (bool) -> True or False (Case-sensitive)

print(f"Title Type: {type(product_title)}")
print(f"Stock Type: {type(stock_quantity)}")
print(f"Price Type: {type(product_price)}")
print(f"Availability Type: {type(is_available)}")
print()

# 3. Dynamic Typing
# Python is dynamically typed, meaning a variable can change its data type at any time
print("--- 3. Dynamic Typing ---")
data_holder = 100
print(f"Initial Value: {data_holder} | Type: {type(data_holder)}")
print()

# 4. Multiple Assignment
# Assigning multiple variables in a single line of code for efficiency
print("--- 4. Multiple Assignment ---")
# Assigning different values to different variables
x, y, z = 10, 20, 30
print(f"x: {x}, y: {y}, z: {z}")

# Assigning the same value to multiple variables at once
gold_score = silver_score = bronze_score = 100
print(f"Gold: {gold_score}, Silver: {silver_score}, Bronze: {bronze_score}")
print()

# 5. Type Casting (Data Type Conversion)
# Converting one data type into another manually using built-in functions
print("--- 5. Type Casting ---")
age_str = "25"
# Converting String to Integer so we can perform math operations
age_int = int(age_str)
print(f"In 5 years, you will be: {age_int + 5} years old")

# Converting Integer to Float
price_int = 50
price_float = float(price_int)
print(f"Integer {price_int} converted to Float: {price_float}")

# Converting Value to Boolean (Any non-zero/non-empty value becomes True)
print(f"Is number 0 True? -> {bool(0)}")
print(f"Is number 1 True? -> {bool(1)}")
print(f"Is empty text '' True? -> {bool('')}")
print(f"Is text 'Hello' True? -> {bool('Hello')}")
print()

# 6. Constants (Naming Agreement)
# Python doesn't have built-in constants. Industry-standard uses ALL-CAPS
# to signal to other programmers that these values should NEVER be changed
print("--- 6. Constants ---")
PI = 3.14159
DATABASE_URL = "https://company.com"
print(f"Constant PI: {PI} | API Endpoint: {DATABASE_URL}")
print()

# 7. Type Hinting (Python 3.5+)
# Explicitly declaring the expected data type
# for preventing bugs and improving auto-complete features in text editors
print("--- 7. Type Hinting ---")
employee_id: int = 1024
employee_name: str = "Jonathan"
is_manager: bool = False

print(f"ID: {employee_id}, Name: {employee_name}, Is Manager: {is_manager}")
print()

# 8. Variable Scope (Global vs Local)
# Variables created outside a function are Global. Variables inside are Local.
print("--- 8. Variable Scope ---")
global_score = 100     # Accessible anywhere in the file

def demonstrate_scope():
  local_score = 50     # Only accessible inside this function
  print(f"Inside function (Local): {local_score}")
  print(f"Inside function (Global): {global_score}")

demonstrate_scope()
# print(local_score) <- This would cause an Error if uncommented because it is local!
print()

# 9. Swapping Variables (The Pythonic Way)
# Exchanging values between two variables instantly without a third temporary variable
print("--- 9. Swapping Variables ---")
glass_a = "Coffee"
glass_b = "Milk"
print(f"Before Swap -> Glass A: {glass_a} | Glass B: {glass_b}")

glass_a, glass_b = glass_b, glass_a       # Swapping operation
print(f"After Swap -> Glass A: {glass_a} | Glass B: {glass_b}")
print()

# 10. Object Reference & Memory Allocation (Advanced)
# Understanding how Python shares memory addresses for collections (Lists/Dicts)
print("--- 10. Object Reference ---")
list_original = [1, 2, 3]
list_copy = list_original         # This does NOT create a new list! It points to the same memory

# Changing the copied list
list_copy.append(4)

print(f"Original List: {list_original}")        # Output: [1, 2, 3, 4] (Surprisingly changed!)
print(f"Copied List: {list_copy}")              # Output: [1, 2, 3, 4]

# The solution: Use .copy() to create a truly independent duplicate
list_true_clone = list_original.copy()
list_true_clone.append(5)

print(f"After .copy() -> Original: {list_original} | True Clone: {list_true_clone}")
print()

